name: dUralChat
main: net.d3vr.dUralChat.Main
version: 0.1
commands:
  duralchat:
    permission: dUralChat.admin
permissions:
  dUralChat.ignore:
    default: op
  dUralChat.ignore:
    default: op